
name: Example
on:
  push:
    branches:
      - main
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Fluent CI CLI
        uses: fluentci-io/setup-fluentci@v5
        with:
          wasm: true
          pipeline: android
          args: setup

      - name: Run Wasm Plugin
        run: |
          fluentci run --wasm bun install
          fluentci run --wasm . android buildRelease